--TEMPORADA
INSERT INTO TEMPORADA VALUES ('2024/2025');
commit;

--EQUIPS
INSERT INTO EQUIP (NOM, TEMP, TIPUS, CAT) VALUES('Mist Riders','2024/2025','M',5);
INSERT INTO EQUIP (NOM, TEMP, TIPUS, CAT) VALUES('Midenburg Crawlers','2024/2025','H',6);
INSERT INTO EQUIP (NOM, TEMP, TIPUS, CAT) VALUES('Caledor Dragons','2024/2025','H',5);
INSERT INTO EQUIP (NOM, TEMP, TIPUS, CAT) VALUES('Hexoatl Priestesses','2024/2025','D',6);
INSERT INTO EQUIP (NOM, TEMP, TIPUS, CAT) VALUES('Lilith Warriors','2024/2025','D',4);
commit;

--EQUIP FEMENÍ CADET (id=5)
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Gloriel','Summerbloom','D',to_date('11/09/2010','dd/mm/yyyy'),'45156898P',NULL,to_date('01/09/2025','dd/mm/yyyy'),'Plaza Estepas 18',NULL);
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Cindy','Piewhistle','D',to_date('18/05/2009','dd/mm/yyyy'),'45156898Q',NULL,to_date('21/06/2025','dd/mm/yyyy'),'Calle Palanquin 97',NULL);
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Karla','von Kill','D',to_date('09/05/2009','dd/mm/yyyy'),'45156898R',NULL,to_date('01/09/2025','dd/mm/yyyy'),'Cta del Duque 29',NULL);
--EQUIP MIX JUVENIL (id=1)
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Estelle','la Veneaux','D',to_date('05/09/2008','dd/mm/yyyy'),'45156898S',NULL,to_date('09/09/2025','dd/mm/yyyy'),'Passeig Infame 13',NULL);
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Roxanna','Darknail','D',to_date('19/02/2008','dd/mm/yyyy'),'45156898T',NULL,to_date('26/08/2025','dd/mm/yyyy'),'Calle la Polvora 21',NULL);
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Varag','Ghoul-Chewer','H',to_date('07/02/2007','dd/mm/yyyy'),'45156899U',NULL,to_date('16/09/2025','dd/mm/yyyy'),'Cta del Duque 27',NULL);
--EQUIP MASCULI JUVENIL (id=3)
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Griff','Oberwald','H',to_date('03/08/2008','dd/mm/yyyy'),'45156898V',NULL,to_date('11/10/2025','dd/mm/yyyy'),'Calle los Agravios 1',NULL);
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Anqi','Panqi','H',to_date('16/11/2007','dd/mm/yyyy'),'45156898W',NULL,to_date('13/10/2025','dd/mm/yyyy'),'Passeig Lustria 21',NULL);
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Barik','BlastFast','H',to_date('11/06/2007','dd/mm/yyyy'),'45156898X',NULL,to_date('01/11/2025','dd/mm/yyyy'),'Calle Germio del Metal 10',NULL);
--EQUIP FEMENÍ SENIOR (id=4)
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Rowana','Darkforest','D',to_date('21/02/2006','dd/mm/yyyy'),'45156898Y',NULL,to_date('08/07/2025','dd/mm/yyyy'),'Calle Naggaroth 7',NULL);
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Willow','Rosebark','D',to_date('13/06/2005','dd/mm/yyyy'),'45156898Z',NULL,to_date('01/10/2025','dd/mm/yyyy'),'Cta Gremio Maderero 21',NULL);
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Karina','von Riesz','D',to_date('26/09/2004','dd/mm/yyyy'),'45156898A',NULL,to_date('19/08/2025','dd/mm/yyyy'),'Calle los Bardos 97',NULL);
--EQUIP MASCULI SENIOR (id=2)
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Wilhelm','Chaney','H',to_date('21/01/2004','dd/mm/yyyy'),'45156898B',NULL,to_date('21/11/2025','dd/mm/yyyy'),'Calle los Bardos 85',NULL);
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Lucian','Swift','H',to_date('11/09/2006','dd/mm/yyyy'),'45156898C',NULL,to_date('06/10/2025','dd/mm/yyyy'),'Cta Gremio Maderero 27',NULL);
INSERT INTO JUGADOR (NOM, COGNOMS, SEXE, DATA_NAIX, ID_LEGAL, IBAN, ANY_FI_REVISIO_MEDICA, ADRECA, FOTO) VALUES('Mighty','Zug','H',to_date('11/09/2004','dd/mm/yyyy'),'45156898D',NULL,to_date('17/10/2025','dd/mm/yyyy'),'Passeig Lustria 7',NULL);
commit;

--ALTA JUGADORS EN EQUIPS
INSERT INTO TITULARS VALUES(1,5,1);
INSERT INTO TITULARS VALUES(2,5,1);
INSERT INTO TITULARS VALUES(3,5,1);
INSERT INTO TITULARS VALUES(4,1,1);
INSERT INTO TITULARS VALUES(5,1,1);
INSERT INTO TITULARS VALUES(6,1,1);
INSERT INTO TITULARS VALUES(7,3,1);
INSERT INTO TITULARS VALUES(8,3,1);
INSERT INTO TITULARS VALUES(9,3,1);
INSERT INTO TITULARS VALUES(10,4,1);
INSERT INTO TITULARS VALUES(11,4,1);
INSERT INTO TITULARS VALUES(12,4,1);
INSERT INTO TITULARS VALUES(13,2,1);
INSERT INTO TITULARS VALUES(14,2,1);
INSERT INTO TITULARS VALUES(15,2,1);
INSERT INTO TITULARS VALUES(6,3,0);
INSERT INTO TITULARS VALUES(7,2,0);
commit;